# Generated by Django 4.1.5 on 2023-04-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_newsitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
