# Generated by Django 4.1.5 on 2023-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('athr', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wntd_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='wanted')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
