# Generated by Django 4.1.5 on 2023-04-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0006_news_tbl_wntd_tbl_delete_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wntd_tbl',
        ),
    ]
