# Generated by Django 4.1.5 on 2023-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0007_delete_wntd_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_tbl',
            name='img',
            field=models.FileField(default=1, upload_to='upload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_tbl',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
