# Generated by Django 4.1.6 on 2023-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0008_news_tbl_img_alter_news_tbl_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreg_tbl',
            name='des',
        ),
    ]
