# Generated by Django 4.1.5 on 2023-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tbl',
            name='gn',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reg_tbl',
            name='lm',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
