# Generated by Django 4.1.5 on 2023-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_reg_tbl_gn_reg_tbl_lm'),
    ]

    operations = [
        migrations.CreateModel(
            name='crime_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=16)),
                ('hdate', models.CharField(max_length=50)),
                ('ltn', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('sts', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('person', models.IntegerField()),
                ('img', models.FileField(upload_to='picture')),
                ('proof', models.CharField(max_length=50)),
                ('idno', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='id')),
                ('agree', models.CharField(max_length=50)),
            ],
        ),
    ]
