# Generated by Django 4.1.5 on 2023-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0003_crime_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='miss_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('nmbr', models.IntegerField()),
                ('alias', models.CharField(max_length=50)),
                ('relnm', models.CharField(max_length=50)),
                ('rlty', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=150)),
                ('gd', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('age1', models.IntegerField()),
                ('yob', models.CharField(max_length=50)),
                ('bb', models.CharField(max_length=50)),
                ('bc', models.CharField(max_length=50)),
                ('wt', models.IntegerField()),
                ('ht', models.IntegerField()),
                ('img', models.FileField(upload_to='missing')),
            ],
        ),
    ]
