# Generated by Django 4.1.5 on 2023-03-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0005_rename_agree_crime_tbl_dt_rename_age1_miss_tbl_nmb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miss_tbl',
            name='nmbr',
        ),
    ]
