# Generated by Django 4.1.5 on 2023-03-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_crime_tbl_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miss_tbl',
            name='img',
        ),
    ]
