# Generated by Django 4.1.5 on 2023-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0009_remove_miss_tbl_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('bt', models.CharField(max_length=50)),
                ('btl', models.CharField(max_length=50)),
                ('bb', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=150)),
                ('q7', models.FileField(upload_to='missing')),
                ('q8', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='crime_tbl',
            name='image',
        ),
        migrations.AddField(
            model_name='miss_tbl',
            name='img',
            field=models.FileField(default=1, upload_to='missing'),
            preserve_default=False,
        ),
    ]
