# Generated by Django 4.1.5 on 2023-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0010_report_tbl_remove_crime_tbl_image_miss_tbl_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_tbl',
            name='q7',
            field=models.FileField(upload_to='image'),
        ),
    ]
