# Generated by Django 4.1.5 on 2023-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0011_alter_report_tbl_q7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_tbl',
            name='gn',
        ),
    ]
