# Generated by Django 4.1.5 on 2023-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0012_remove_reg_tbl_gn'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_tbl',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miss_tbl',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report_tbl',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
