# Generated by Django 4.1.5 on 2023-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0015_remove_miss_tbl_add_remove_miss_tbl_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_tbl',
            name='sts',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
