# Generated by Django 4.1.5 on 2023-04-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0016_crime_tbl_sts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime_tbl',
            name='sts',
        ),
    ]
