# Generated by Django 4.1.5 on 2023-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0017_remove_crime_tbl_sts'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_tbl',
            name='sts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miss_tbl',
            name='sts_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report_tbl',
            name='sts_r',
            field=models.BooleanField(default=False),
        ),
    ]
