# Generated by Django 4.1.5 on 2023-04-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0018_crime_tbl_sts_miss_tbl_sts_m_report_tbl_sts_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime_tbl',
            name='sts',
        ),
        migrations.RemoveField(
            model_name='miss_tbl',
            name='sts_m',
        ),
        migrations.RemoveField(
            model_name='report_tbl',
            name='sts_r',
        ),
    ]
